### ISSUE TITLE
Morning review: team magpies

### ISSUE THREAD

**Issue by enelesmai** [Zibilyonik/stay-in-touch#9]
Very good job so far Onur! Just some things to do:

* Fix path for Cancel and Delete button in your index view

Add destroy to your routes, and try to check your path with **rake routes** so you can see the expected parameters.
Good luck!

**Comment by Zibilyonik** [comment]
Hello, and thank you very much for the feedback! The button path issues and the routing issues have been fixed 👍 Hope you enjoy the project!
